version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/src/cibmangotree/gui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
